### ISSUE TITLE
Add parameter to specify goa loader class

### ISSUE THREAD

**Issue by Shalsh23** [RENCI-AUTOMAT/Data_services#102]
The current loadGOA class is hardcoded with a call to the PlantGOA class. A parameter needs to be added to specify whether plant of human GO annotations need to be loaded.

Ref: https://github.com/RENCI-AUTOMAT/Data_services/blob/325e3c2cba1e541c598faed2c9dc1705fa1938d7/parsers/GOA/src/loadGOA.py#L227

**Comment by cbizon** [comment]
What's the status on this @Shalsh23 ?

**Comment by EvanDietzMorris** [comment]
I would consider this not worth spending time on. This is referring to invoking the parser directly, which is not intended in normal usage. Calling the loadmanager with the appropriate source ID already accomplishes the same thing. We could actually remove the __main__ and argsparse portions from all of the parsers to avoid confusion.
