### ISSUE TITLE
Convert all labels to CamelCase, edges to biolink:*

### ISSUE THREAD

**Issue by cbizon** [RENCI-AUTOMAT/Data_services#15]
Need this for biolink compliance.  Can do on the live graphs for now, but should also update our data makers.

**Comment by PhillipsOwen** [comment]
Can you please provide an example for a label (node? edge?) that needs camel case? this could be something that may need implementation in node normalization.

Edge normalization already returns biolinks:* edge labels (when it can). if these need to be CamelCased it should probably be implemented there.

**Comment by cbizon** [comment]
OK, so the edges are fine, but the node labels need to be in the format `biolink:ChemicalSubstance`.  You're right that this is actually a node-normalizer problem.  I'll make a ticket there (but leaving this one open as a reminder that everything needs updated).
