### ISSUE TITLE
"biolink" labels on nodes

### ISSUE THREAD

**Issue by cbizon** [RENCI-AUTOMAT/Data_services#17]
We have nodes that have labels "biolink" and "molecularly interacts with".  This is clearly an error of some kind.

**Comment by PhillipsOwen** [comment]
can you narrow it down to a specific dataset?

**Comment by cbizon** [comment]
Not obvious, because they don't seem to have any edges

**Comment by PhillipsOwen** [comment]
i did not find this occurring in any of the data services datasets.

**Comment by PhillipsOwen** [comment]
this is complete for data services datasets. PR is #35
