### ISSUE TITLE
No labels on taxon nodes

### ISSUE THREAD

**Issue by cbizon** [RENCI-AUTOMAT/Data_services#20]
This may be a nodenormalization problem.

**Comment by PhillipsOwen** [comment]
Presuming that this data was discovered on the covid graph, I ran this query which did not return any rows:

match (n1) where n1.id=~".*NCBITaxon.*" and (n1.name=null or n1.name="") return n1 limit 10

**Comment by cbizon** [comment]
Hmm, I noticed this in the browser.   Looking around, it appears that the. nodes do have names, the browser was just not displaying them. 

FWIW,  I suspect that this query would be faster:
match (n1:organism_taxon) where (n1.name = null or n1.name="") return n1 limit 10
