### ISSUE TITLE
nodes with no edges

### ISSUE THREAD

**Issue by cbizon** [RENCI-AUTOMAT/Data_services#21]
match (g) where not g:Concept and size((g)-[]-()) = 0 return count(distinct g)

**Comment by cbizon** [comment]
31648

**Comment by PhillipsOwen** [comment]
covid graph?

**Comment by cbizon** [comment]
robokopkg, which I think is the covidgraph
________________________________

**Comment by PhillipsOwen** [comment]
I am trying to isolate the datasets that these are coming from. i am using a unique property on each node to infer the source.
 - molecular_formula: pubchem, kegg, chebi
 - locus_group: hgnc, ensembl

the gtop nodes to not appear to have any normalization. could this also be the issue for the others?

**Comment by PhillipsOwen** [comment]
this is an interesting query that Yaphet shared with me:
match (g) where not g:Concept and size((g)-[]-()) = 0 return count(*), labels(g)

that returns the following on robokopkg:
7484	["named_thing", "biological_entity", "chemical_substance", "molecular_entity"]
3655	["named_thing", "biological_entity", "molecular_entity", "gene", "gene_or_gene_product", "macromolecular_machine", "genomic_entity"]
16923	["named_thing"]
150	["named_thing", "biological_entity", "disease_or_phenotypic_feature", "phenotypic_feature"]
358	["named_thing", "biological_entity", "disease", "disease_or_phenotypic_feature"]
249	["named_thing", "biological_entity", "biological_process", "biological_process_or_activity"]
4	["named_thing", "biological_entity", "biological_process_or_activity", "molecular_activity"]
447	["named_thing", "organismal_entity", "biological_entity", "anatomical_entity", "cellular_component"]
8	["named_thing", "organismal_entity", "biological_entity", "cell", "anatomical_entity"]
8	["named_thing", "organismal_entity", "biological_entity", "anatomical_entity"]
2328	["named_thing", "ontology_class", "organism_taxon"]
17	["named_thing", "biolink", "in_taxon"]
17	["named_thing", "biolink", "molecularly_interacts_with"]

covid specific datasets missing edge counts:
* cord-scibite-v6, 0
* cord-scigraph-v12, 18468
* Viral Proteome/UniRef, 0 
* Intact, 0 
* Covid phenotypes csv, 0
* drug bank clinical trial drugs (no automat?)

other automat datasets missing edge counts:
* chem-norm, 260930
* topmed, 0
* kegg, 119245
* hmdb, 156856
* human goa, 0
* pharos (old), 148962
* mychem, 112271
* ctd, 98033
* gtopdb, 110064
* hetio, 67554
* uberongraph, 11929
* textminigkp, 126
* hgnc, 19946
* panther, 0
* chembio, 101997
* foodb, 6142

**Comment by cbizon** [comment]
I think this is something we should be collecting as a test for each KG.   DO any of the data services graphs have non-edge nodes?

**Comment by PhillipsOwen** [comment]
All datasets have been tested and corrected where necessary. a project card has been created for the deployment of all affected datasets.

**Comment by PhillipsOwen** [comment]
reopened for datasets that are not currently parsed in data services.

**Comment by PhillipsOwen** [comment]
this is complete. PR is #35
