### ISSUE TITLE
taxons mistyped as genes [intact]

### ISSUE THREAD

**Issue by cbizon** [RENCI-AUTOMAT/Data_services#25]
On robokopkg:

match (g:gene)-[x:in_taxon]->(gg:gene) return gg.id

"NCBITaxon:226127"
--
"NCBITaxon:1289469"

I think that these two are probably not normalizing correctly, but the type being assigned them is gene for some reaason.

**Comment by cbizon** [comment]
Right, but something is then assigning it an incorrect type

**Comment by PhillipsOwen** [comment]
i tracked this one down. 

the intact code tries to "save" nodes that didnt normalize by giving them the defaults values for the category. looking at the normalization results indicates that 2 taxons did not normalize.

the "save" process did not expect ncbi taxons to not normalize so it was given the default uniprotkb categories (gene, gene_product, etc.).

i will modify the code to insure that curie categories are defaulted to the appropriate value.
