### ISSUE TITLE
GTEX: collapse edges

### ISSUE THREAD

**Issue by cbizon** [RENCI-AUTOMAT/Data_services#3]
GTEx edges are per-tissue.  So you might have variantA - increases expression of - geneG in the liver and in the lung.  This will show up as 2 edges, each with a property saying the tissue type.

Because eqtls frequently (almost universally) are multi-tissue, this leads to a lot of 'redundant' edges.  So these should be collapsed into a single edge (per type) and tissue made into an array property on that edge.

**Comment by PhillipsOwen** [comment]
could there ever be a condition where allele A increases the expression of gene G in tissue T1 but decreases the expression in tissue T2?

**Comment by cbizon** [comment]
yes, and those would have to group independently.  Could also be a modifies splicing in a third tissue.

**Comment by PhillipsOwen** [comment]
this is complete.
