### ISSUE TITLE
Treats edges pointed the wrong direction

### ISSUE THREAD

**Issue by cbizon** [RENCI-AUTOMAT/Data_services#39]
For relationships coming from uberongraph with MONDO:disease_responds_to, the edges are pointing from disease to chemical_substance:

match (d:disease)-[:treats]->(c:chemical_substance) return * limit 10

**Comment by PhillipsOwen** [comment]
the robokopkg graph is the graph that contains this incorrect data. the data in this graph was populated using the legacy robokop services (no data services data).

when i get to refactoring the ubergraph data in data services for the load manager i will make a point of insuring this is taken care of.

**Comment by cbizon** [comment]
Fixed
