### ISSUE TITLE
gene / cellular component relation in human-goa

### ISSUE THREAD

**Issue by cbizon** [RENCI-AUTOMAT/Data_services#41]
According to automat/predicates, this is a related_to edge.  Shouldn't it be a part_of or something else more specific?

**Comment by PhillipsOwen** [comment]
i believe this is what edge norm falls back to when it doesnt mormalize.

**Comment by PhillipsOwen** [comment]
this was corrected in the latest refactor. 

the code had specified "has_part" to be associated to "RO:0000051". this was changed to "RO:0001019"

note the latest parse output does not have any "related_to" predicates.
