### ISSUE TITLE
GOA: edge source and source database are incorrect

### ISSUE THREAD

**Issue by cbizon** [RENCI-AUTOMAT/Data_services#5]
The source database is listed as "http://github"

The edge_source is also a URL.

**Comment by PhillipsOwen** [comment]
i dont see this in the datasets i did for viral proteome or human GOA. where are you seeing this?

**Comment by cbizon** [comment]
It's in the graph on robokopdev

**Comment by PhillipsOwen** [comment]
I believe this is another loading issue as this data does not exist on the KGX source. 

also note that there is a mixture of the data types in the edge_source and source_database columns. there are single element arrays and a single values in these columns.
