### ISSUE TITLE
HMDB data review

### ISSUE THREAD

**Issue by PhillipsOwen** [RENCI-AUTOMAT/Data_services#57]
Comments/issues on data review.

**Comment by cbizon** [comment]
The UniProt nodenorm misses are apparently obsolete entries.   OK to lose those.

**Comment by cbizon** [comment]
The HMDB terms are more trouble. For some reason unichem doesn't have these hmdb ids even though they have inchikeys.  Added nn issue https://github.com/TranslatorSRI/NodeNormalization/issues/66

**Comment by cbizon** [comment]
The OMIM ids seem to be to genes.  The most recent build of NN (not yet deployed) should pick these up.

**Comment by cbizon** [comment]
Some of the OMIMs are diseases, but they seem to also be in the most recent (undeployed) build.

**Comment by cbizon** [comment]
The json file doesn't have normalization results in it.  Can you regenerate, @PhillipsOwen ?
