### ISSUE TITLE
PHAROS: gene_associated_with_condition between two genes

### ISSUE THREAD

**Issue by cbizon** [RENCI-AUTOMAT/Data_services#6]
match (g:gene)-[:gene_associated_with_condition]->(gg:gene) return *

Should return no results.  The object should be a condition. There are several results however.   Most of them are self-links for some reason (i.e. g == gg)

**Comment by PhillipsOwen** [comment]
i am also seeing this data in the automat graph. so the parser may be at fault with this one.

also seeing that the edge properties arent following the KGX recommendations (id, subject, relation, edge_label, object, source_database)

**Comment by PhillipsOwen** [comment]
this is related to issue #10 and will be repaired when the data is refactored for KGX output

**Comment by PhillipsOwen** [comment]
this is complete.
