### ISSUE TITLE
Ubergraph data review

### ISSUE THREAD

**Issue by PhillipsOwen** [RENCI-AUTOMAT/Data_services#61]
Comments/issues on data review.

**Comment by cbizon** [comment]
The kgx files look fine, but the current plater is missing stuff?  Take this edge for example:

UberGraph_1_norm_edges.json:{"id": "d367f35a2f1a91844474fd76b43f1fde", "subject": "GO:0007015", "predicate": "biolink:has_participant", "object": "GO:0005884", "relation": "RO:0000057", "source_database": "UberGraph properties-nonredundant"}
UberGraph_1_norm_edges.json:{"id": "d367f35a2f1a91844474fd76b43f1fde", "subject": "GO:0007015", "predicate": "biolink:affects", "object": "GO:0005884", "relation": "RO:0002592", "source_database": "UberGraph properties-nonredundant"}


I don't think that they are in the currently posted automat, and I don't know why not.

**Comment by PhillipsOwen** [comment]
this appears to be related to the predicate 'biolink:has_participant' and not the subject/object ids. looking into it.

**Comment by cbizon** [comment]
These edges are in the current graph
