### ISSUE TITLE
Intact: include methods as edge properties

### ISSUE THREAD

**Issue by cbizon** [RENCI-AUTOMAT/Data_services#7]
In the IntAct database, there are methods that tell you how the interactions are discovered (e.g. antitag coimmunity precipitation).  Also there are PMIDs for interactions.   Neither of these is making it into the robokop graph, but they should occur as edge properties.

**Comment by PhillipsOwen** [comment]
here are a couple lines of the kgx edge file.

id	subject	relation	edge_label	publications	detection_method	object	source_database
cadb17e2168cd064d3390e17c1ff1910	NCBIGene:6607	biolink:molecularly_interacts_with	biolink:molecularly_interacts_with	PMID:9323129	MI:0018|MI:0096|MI:0049	NCBIGene:8487	IntAct

as you can see the pmids are in place. i will look into the interaction discoveries.

i thought that the intact and goa files were only imported into the covid graph.

**Comment by cbizon** [comment]
It looks like the interaction discovery methods are also in place.  So this appears to be less a data issue and more of a loading problem?

They are in the covid graph, I misspoke in the original report.

**Comment by PhillipsOwen** [comment]
i am looking at my side of it now. the pubmed IDs and the MI CURIEs give us the provenance and detection methods of the interaction. 

I agree that it is a loading issue on the covid graph side.

**Comment by PhillipsOwen** [comment]
this should be fixed in this commit: https://github.com/TranslatorIIPrototypes/robo-commons/commit/bb936ccf98ccf9d27df9a2b0d8126c7064096fac#diff-6c41dcc569a9d96c6639aaf399ad16b555edb5855df0e17a0bcd73a267b2286a
