### ISSUE TITLE
DRY

### ISSUE THREAD

**Issue by cbizon** [RENCI-AUTOMAT/Data_services#72]
There are many places in data services that violate https://en.wikipedia.org/wiki/Don%27t_repeat_yourself

Specifically, the writing code for KGX seems to appear without fail in many parsers.  As does the get name function.  These could easily be moved up to the superclass and overriden if required.

**Comment by cbizon** [comment]
How would we characterize the current state here?

**Comment by EvanDietzMorris** [comment]
Most of the worst offenders are handled already but there is still more that should be done. 

At least these should be addressed:
  - Any parsers using source-specific data fetching methods from the utils class should be cleaned up. 
  - Several parsers still need more substantial work and have not been fully converted to the latest interface format. 
  - The merging algorithm used by the file normalizer should be converted to use the same code as the graph builder.
