### ISSUE TITLE
Never lose edges for normalization

### ISSUE THREAD

**Issue by cbizon** [RENCI-AUTOMAT/Data_services#92]
There is a bug in bl-lookup where it will sometimes return {} when we try to look up an edge.  

We should always use `biolink:related_to` in that case.   We should never lose an edge for lack of normalization.

**Comment by EvanDietzMorris** [comment]
We had this behavior before but removed it with the assumption bl-lookup would always return something. 

It seems reasonable to have a fallback in both places. I've added it back in here: 
https://github.com/RENCI-AUTOMAT/Data_services/commit/5c64cc79aacc1c93d749a58ae01cc77700e74c2c
